[package]
name    = "kprobe"
version = "0.8.1"
authors = ["Will <will@kentik.com>"]
links   = "kflow"
build   = "build.rs"

[dependencies]
clap      = "2.25.1"
libc      = "0.2.27"
time      = "0.1.38"
byteorder = "1.1.0"
nom       = "2.2.1"
pnet      = "0.18.0"
pcap      = "0.5.7"
rand      = "0.3.16"

http-muncher = "0.3.1"

[profile.release]
lto   = true
debug = true
