[package]
name    = "kprobe"
version = "0.1.0"
authors = ["Will <will@kentik.com>"]
links   = "kflow"
build   = "build.rs"

[dependencies]
clap      = "2.20.5"
pnet      = "0.16.0"
libc      = "0.2.21"
byteorder = "1.0.0"
nom       = "2.1.0"
chrono    = "0.3.0"
pcap      = "0.5.7"

[profile.release]
lto = true
