[package]
name    = "kprobe"
version = "1.1.0"
authors = ["Will <will@kentik.com>"]
links   = "kflow"
build   = "build.rs"

description = """

Kentik host agent - please see https://kb.kentik.com/Bd03.htm for detailed
documentation of flags, options, and recommended configuration.
"""

[dependencies]
clap      = "2.31.2"
libc      = "0.2.40"
time      = "0.1.40"
byteorder = "1.1.0"
nom       = "2.2.1"
pnet      = "0.21.0"
pcap      = "0.7.0"
rand      = "0.4.2"

http-muncher = "0.3.1"

[profile.release]
lto   = true
debug = true
