[package]
name    = "kprobe"
version = "1.3.0"
authors = ["Will <will@kentik.com>"]
edition = "2018"
build   = "build.rs"

license     = "PROPRIETARY"
description = """

Kentik host agent - please see https://kb.kentik.com/Bd03.htm for detailed
documentation of flags, options, and recommended configuration.
"""

[dependencies]
clap         = "2.31.2"
errno        = "0.2.3"
libc         = "0.2.40"
time         = "0.1.40"
byteorder    = "1.1.0"
nom          = "3.2.1"
pnet         = "0.21.0"
pcap         = "0.7.0"
rand         = "0.4.2"
http-muncher = "0.3.1"
serde_bytes  = "0.10.4"
rmp-serde    = "0.13.7"
jemallocator = "0.3.0"

[dependencies.serde]
version  = "1.0.84"
features = ["derive"]

[profile.release]
lto   = true
debug = true

[package.metadata.deb]
assets = [
  ["target/x86_64-unknown-linux-musl/release/kprobe", "usr/bin/", "755"],
]

[package.metadata.rpm.cargo]
buildflags = ["--release", "--target", "x86_64-unknown-linux-musl", "--bin", "kprobe"]

[package.metadata.rpm.targets]
"../x86_64-unknown-linux-musl/release/kprobe" = { path = "/usr/bin/kprobe" }
