[package]
name    = "kprobe"
version = "0.1.0"
authors = ["Will <will@kentik.com>"]
links   = "kflow"
build   = "build.rs"

[dependencies]
clap      = "2.23.2"
pnet      = "0.17.0"
libc      = "0.2.21"
byteorder = "1.0.0"
nom       = "2.2.1"
chrono    = "0.3.0"
time      = "0.1.36"
pcap      = "0.5.7"

[profile.release]
lto   = true
debug = true
