[package]
name    = "kprobe"
version = "0.2.0"
authors = ["Will <will@kentik.com>"]
links   = "kflow"
build   = "build.rs"

[dependencies]
clap      = "2.24.1"
pnet      = "0.17.1"
libc      = "0.2.22"
byteorder = "1.0.0"
nom       = "2.2.1"
time      = "0.1.37"
pcap      = "0.5.7"

http-muncher = "0.3.1"

[profile.release]
lto   = true
debug = true
