[package]
name    = "kprobe"
version = "2.0.0"
authors = ["Will <will@kentik.com>"]
edition = "2018"
build   = "build.rs"

license     = "PROPRIETARY"
description = """

Kentik host agent - please see https://kb.kentik.com/Bd03.htm for detailed
documentation of flags, options, and recommended configuration.
"""

[dependencies]
byteorder    = "1.3.1"
clap         = "2.33.0"
env_logger   = "0.6.1"
errno        = "0.2.4"
http-muncher = "0.3.2"
libc         = "0.2.51"
log          = "0.4.6"
nom          = "3.2.1"
pnet         = "0.22.0"
pcap         = "0.7.0"
rand         = "0.6.5"
ring         = "0.16.20"
time         = "0.1.42"
url          = "1.7.2"

[dependencies.kentik-api]
git = "ssh://git@github.com/kentik/kentik-api-rust"
tag = "0.0.3"


[target.'cfg(not(target_arch = "arm"))'.dependencies]
jemallocator = "0.3.0"

[build-dependencies]
anyhow       = "1.0.55"
platforms    = "2.0.0"

[profile.release]
lto   = true
debug = true
