[package]
name    = "kprobe"
version = "0.1.0"
authors = ["Will <will@kentik.com>"]

[dependencies]
clap      = "2.20.0"
pnet      = "0.16.0"
libc      = "0.2.18"
byteorder = "1.0.0"
nom       = "2.0.1"

[profile.release]
lto = true