[package]
name    = "kprobe"
version = "0.9.0-rs"
authors = ["Will <will@kentik.com>"]
links   = "kflow"
build   = "build.rs"

description = """

Kentik host agent - please see https://kb.kentik.com/Bd03.htm for detailed
documentation of flags, options, and recommended configuration.
"""

[dependencies]
clap      = "2.26.2"
libc      = "0.2.31"
time      = "0.1.38"
byteorder = "1.1.0"
nom       = "2.2.1"
pnet      = "0.19.0"
pcap      = "0.5.7"
rand      = "0.3.16"

http-muncher = "0.3.1"

[profile.release]
lto   = true
debug = true
