[package]
name    = "kprobe"
version = "0.3.5"
authors = ["Will <will@kentik.com>"]
links   = "kflow"
build   = "build.rs"

[dependencies]
clap      = "2.24.2"
libc      = "0.2.23"
time      = "0.1.37"
byteorder = "1.0.0"
nom       = "2.2.1"
pnet      = "0.17.1"
pcap      = "0.5.7"

http-muncher = "0.3.1"

[profile.release]
lto   = true
debug = true
