[package]
name    = "kprobe"
version = "1.4.0"
authors = ["Will <will@kentik.com>"]
edition = "2018"
build   = "build.rs"

license     = "PROPRIETARY"
description = """

Kentik host agent - please see https://kb.kentik.com/Bd03.htm for detailed
documentation of flags, options, and recommended configuration.
"""

[dependencies]
byteorder    = "1.3.1"
clap         = "2.33.0"
env_logger   = "0.6.1"
errno        = "0.2.4"
http-muncher = "0.3.2"
jemallocator = "0.3.0"
libc         = "0.2.51"
log          = "0.4.6"
nom          = "3.2.1"
pnet         = "0.22.0"
pcap         = "0.7.0"
rand         = "0.6.5"
time         = "0.1.42"
url          = "1.7.2"

[dependencies.kentik-api]
git = "ssh://git@github.com/kentik/kentik-api"
tag = "0.0.2"

[profile.release]
lto   = true
debug = true

[package.metadata.deb]
assets = [
  ["target/x86_64-unknown-linux-musl/release/kprobe", "usr/bin/", "755"],
]

[package.metadata.rpm.cargo]
buildflags = ["--release", "--target", "x86_64-unknown-linux-musl", "--bin", "kprobe"]

[package.metadata.rpm.targets]
"../x86_64-unknown-linux-musl/release/kprobe" = { path = "/usr/bin/kprobe" }
