name: kprobe
description: kprobe
version: TAG
target:
  build: CC=x86_64-linux-musl-gcc cargo build --release --target x86_64-unknown-linux-musl
docker:
  build:
    base: kt-build-rust:master
  run:
    base: kt-run-generic-bullseye:master
notifications:
  slack:
    channel: will-test
