name: kprobe
description: kprobe
version: TAG
target:
  build: rustup update && cargo build --release --target x86_64-unknown-linux-musl
docker:
  build:
    base: kt-build-rust:master
notifications:
  slack:
    channel: "will-test"
