name: kprobe
description: kprobe
# version: TAG
target:
  build: cargo build --release --target x86_64-unknown-linux-musl
docker:
  build:
    base: kt-build-rust:master
depends:
notifications:
  slack:
    channel: "will-test"
