name: package

inputs:
  artifact:
    required: true
  version:
    required: true
  arch:
    required: true
  format:
    required: true

outputs:
  bundle:
    value: ${{ steps.bundle.outputs.bundle }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
    - uses: kentik/pkg@master
      with:
        name: ${{ github.event.repository.name }}
        version: ${{ inputs.version }}
        arch: ${{ inputs.arch }}
        format: ${{ inputs.format }}
        package: package.yml
      id: package
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.package.outputs.package }}
        path: ${{ steps.package.outputs.package }}
