FROM ghcr.io/cross-rs/x86_64-unknown-freebsd:0.2.4

ARG PROTOBUF=v28.2/protoc-28.2-linux-x86_64.zip

RUN apt-get update && apt-get install -y capnproto bsdtar

RUN curl --retry 3 -sSfL http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/14.1-RELEASE/base.txz | tar xJvf - -C /usr/local/x86_64-unknown-freebsd12/lib --strip-components 3 ./usr/lib/libkvm.a ./usr/lib/libdevstat.a ./usr/lib/libmemstat.a

RUN curl --retry 3 -sSfL https://github.com/protocolbuffers/protobuf/releases/download/$PROTOBUF | bsdtar -xvf - -C /usr/local

RUN chmod a+x /usr/local/bin/protoc
